apiVersion: v1
name: core
description: This chart will deploy Stellar Core node
version: 0.6.1
appVersion: "26.0.1-3109.e78c97ed0.jammy"
maintainers:
  - name: Stellar Development Foundation
sources:
  - https://github.com/stellar/stellar-core
  - https://github.com/stellar/helm-charts
