global:
  ## String to use to explicitly set namespace name in manifests.
  ## Useful for those using "helm template" to render templates
  # namespace: mynamespace

  ## Stellar network to use. When set to "testnet" or "pubnet" default
  ## recommended config will be used.
  ## When set to any other value you have to provide extra settings:
  ##   - global.historyArchiveUrls
  ##   - global.networkPassphrase
  ##   - core.coreConfig
  network: testnet # XXX currently testnet and pubnet are not supported

  # networkPassphrase: "My Stellar Network; June 2020"

  ## String to partially override common.fullname template (will maintain the release name)
  ##
  # nameOverride:

  ## String to fully override common.fullname template
  ##
  # fullnameOverride:

  ## List of pre-existing image Pull Secrets to use
  # imagePullSecrets:
  # - imagepullsecret1
  # - imagepullsecret2

  image:
    core:
      registry: docker.io
      repository: stellar/stellar-core
      ## Optional tag. Defaults to the appVersion from Chart.yaml
      # tag: 1.2.3

      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: Always
    coreExporter:
      registry: docker.io
      repository: stellar/stellar-core-prometheus-exporter
      tag: latest
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: Always

    ## We use nginx for the history proxy service
    nginx:
      registry: docker.io
      repository: nginx
      tag: 1.23
      ## Specify a imagePullPolicy
      ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
      ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: Always

core:
  ## See global.image.core for image settings

  ## List of extra CLI arguments to provide to the stellar-core binary
  extraCliArgs: []

  ## Required when global.network is set to non-standard value
  ## Also useful if you want to provide non-standard config
  # coreConfig:

  ## For production use cases we recommend at least 2 replicas
  replicaCount: 1

  ## Core pods do not need to be initialized in a specific order
  podManagementPolicy: Parallel

  ## Uncomment to use custom service account
  # serviceAccountName: default

  ## Additional annotations or labels to add the Deployment template
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "6000"
  # labels:
  #   environment: "dev"
  #   mylabel1: "myvalue1"

  persistence:
    enabled: false
    storageClass: default
    size: 100G

  ## Validators need to publish history archives. historyProxy section
  # will make the chart deplo reverse proxy nginx container
  historyProxy:
    enabled: false

    ## Path to serve over http
    # localPath: /var/lib/stellar/local_archive
    ## Uncomment to set resource limits
    #resources:
    #  limits:
    #    cpu: 250m
    #    memory: 512Mi
    #  requests:
    #    cpu: 50m
    #    memory: 50Mi

    ingress:
      enabled: false
      host: history-proxy.example.com
      ## Extra annotations to add to the Ingress object
      #annotations:
      #  kubernetes.io/ingress.class: "public"
      #  cert-manager.io/cluster-issuer: "default"
      ## Extra labels to add to the Ingress object
      #labels:
      #  mylabel: myvalue

  ## Uncomment to set resource limits
  #resources:
  #  limits:
  #    cpu: 2
  #    memory: 4Gi
  #  requests:
  #    cpu: 250m
  #    memory: 2Gi

  coreExporter:
    ## Common prometheus config examples do not allow it to scrape 2 ports
    ## If you'd like to scrape both horizon and core metrics example
    ## workarounds can be found here:
    ##   https://github.com/prometheus/prometheus/issues/3756#issuecomment-362266296
    ##   https://github.com/prometheus/prometheus/issues/3756#issuecomment-874043080
    ## If you'd like to have prometheus
    enabled: true

    ## See global.image.coreExporter for image settings

    ## Uncomment to set resource limits
    #resources:
    #  limits:
    #    cpu: 250m
    #    memory: 512Mi
    #  requests:
    #    cpu: 50m
    #    memory: 128Mi

  ## Example affinity
  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchLabels:
  #           app: account-viewer-v2
  #       topologyKey: kubernetes.io/hostname
  affinity: {}

  ## Example podDisruptionBudget
  # podDisruptionBudget:
  #   minAvailable: 1
  podDisruptionBudget: {}
