{{- if .Values.cnpg.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon.cnpgAppSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  username: {{ required "cnpg.auth.username is required when cnpg.enabled=true" .Values.cnpg.auth.username | quote }}
  password: {{ required "cnpg.auth.password is required when cnpg.enabled=true" .Values.cnpg.auth.password | quote }}
{{- end }}
