{{- if .Values.cnpg.enabled }}
{{- include "horizon.validateCnpgAuthBootstrapConfig" . }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "horizon.cnpgClusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- include "horizon.cnpgClusterSpec" . | nindent 2 }}
{{- end }}
