{{- $clusterSpec := default (dict) .Values.cnpg.cluster.spec -}}
{{- if and .Values.cnpg.enabled (not (hasKey $clusterSpec "bootstrap")) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon.cnpgAppSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  username: {{ default "horizon" .Values.cnpg.auth.username | quote }}
  password: {{ required "cnpg.auth.password is required when cnpg.enabled=true" .Values.cnpg.auth.password | quote }}
{{- end }}
