{{- if and .Values.cnpg.enabled (or (and .Values.ingest.enabled (not .Values.ingest.existingSecret)) (and .Values.web.enabled (not .Values.web.existingSecret))) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "horizon.defaultDatabaseSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "horizon.databaseUrl" . | quote }}
{{- end }}
