{{- if .Values.web.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "common.fullname" . }}-web
    chart: {{ include "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "common.fullname" . }}-web
        release: {{ .Release.Name }}
        horizon_network: {{ .Values.global.network }}
        {{- if .Values.web.labels }}
        {{- range $key, $value := .Values.web.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      {{- if .Values.web.annotations }}
      annotations:
        {{- range $key, $value := .Values.web.annotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.web.serviceAccountName }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.global.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: horizon
        image: {{ include "common.horizonImage" . | quote }}
        {{- if .Values.web.cliArgs }}
        args:
        {{- range $flag := .Values.web.cliArgs }}
        - {{ $flag | quote }}
        {{- end }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.web.horizonConfig.port }}
          name: horizon
        - containerPort: {{ .Values.web.horizonConfig.adminPort }}
          name: metrics
        envFrom:
        - secretRef:
            name: {{ .Values.web.existingSecret }}
        - configMapRef:
            name: {{ include "common.fullname" . }}-web-env
        readinessProbe:
          httpGet:
            port: {{ .Values.web.horizonConfig.port }}
            path: /health
          initialDelaySeconds: 5
          timeoutSeconds: 5
        {{- if .Values.web.resources }}
        resources: {{ toYaml .Values.web.resources | nindent 10 }}
        {{- end }}
{{- end }}
