---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "common.fullname" . }}-var-lib-stellar-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sorobanRpc.persistence.size | quote }}
  storageClassName: {{ .Values.sorobanRpc.persistence.storageClass }}
