---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ template "common.fullname" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  # Currently Soroban RPC doesn't support HA deployments.
  # For that reason we hardcode replicas value at 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "common.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "common.fullname" . }}
        release: {{ .Release.Name }}
      {{- if (.Values.sorobanRpc).labels }}
        {{- range $key, $value := .Values.sorobanRpc.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      {{- end }}
      {{- if (.Values.sorobanRpc).annotations }}
      annotations:
        {{- range $key, $value := .Values.sorobanRpc.annotations }}
          {{ $key }}: {{ $value | quote }}
          {{- end }}
      {{- end }}
    spec:
      {{- if (.Values.sorobanRpc).serviceAccountName }}
      serviceAccountName: {{ .Values.sorobanRpc.serviceAccountName | default "default" }}
      {{- end }}
      {{- if (.Values.global).imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: soroban-rpc
        image: {{ include "common.sorobanRpcImage" . | quote }}
        args: ["--config-path", "/config/soroban-rpc.cfg"]
        imagePullPolicy: {{ .Values.global.image.sorobanRpc.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        {{- if (.Values.sorobanRpc.persistence).enabled }}
        - name: volume-var-lib-stellar
          mountPath: /var/lib/stellar
        {{- end }}
        ports:
        - containerPort: 8000
          name: soroban-rpc
        - containerPort: 6061
          name: admin-port
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                curl --location --request POST 'http://127.0.0.1:8000/' \
                  --header 'Content-Type: application/json' \
                  --data-raw '{
                    "jsonrpc": "2.0",
                    "id": 10235,
                    "method": "getHealth"
                  }' | grep "jsonrpc"
        {{- if (.Values.sorobanRpc).resources }}
        resources:
{{ toYaml .Values.sorobanRpc.resources | indent 10 }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ template "common.fullname" . }}
      {{- if (.Values.sorobanRpc.persistence).enabled }}
      - name: volume-var-lib-stellar
        persistentVolumeClaim:
          claimName: {{ template "common.fullname" . }}-var-lib-stellar-pvc
      {{- end }}
