---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    app: {{ template "common.fullname" . }}
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: soroban-rpc
      port: {{ include "common.rpcPort" . }}
      targetPort: {{ include "common.rpcPort" . }}
  selector:
    app: {{ template "common.fullname" . }}
